"""ROADMAP parser: extract next unshipped item for self-build loop."""

from __future__ import annotations

import re
from pathlib import Path

from .store import CODE_ROOT

ROADMAP_PATH = CODE_ROOT / "docs" / "ROADMAP.md"


def parse_roadmap() -> dict:
    """Parse ROADMAP.md and extract structured data about WC items.
    
    Returns:
        dict with keys:
            - items: list of dicts with id, name, status, acceptance criteria
            - next_unshipped: dict for the next WC item that is not shipped, or None
    """
    if not ROADMAP_PATH.exists():
        return {"items": [], "next_unshipped": None}
    
    text = ROADMAP_PATH.read_text(encoding="utf-8")
    lines = text.split("\n")
    
    items = []
    current = None
    in_acceptance = False
    acceptance_lines = []
    
    for line in lines:
        # Match WC-N section headers
        # Example: ### **WC-1: True Parallel Multi-Agent** ✅ SHIPPED
        wc_match = re.match(r"^###\s+\*\*WC-(\d+):\s+([^*]+)\*\*\s*(.*)", line)
        if wc_match:
            # Save previous item
            if current:
                current["acceptance"] = acceptance_lines
                items.append(current)
            
            wc_num = int(wc_match.group(1))
            wc_name = wc_match.group(2).strip()
            wc_status = wc_match.group(3).strip()
            
            shipped = "✅" in wc_status or "SHIPPED" in wc_status.upper()
            
            current = {
                "id": f"WC-{wc_num}",
                "num": wc_num,
                "name": wc_name,
                "shipped": shipped,
                "status_line": wc_status,
                "acceptance": []
            }
            in_acceptance = False
            acceptance_lines = []
            continue
        
        # Match acceptance criteria section
        if current and re.match(r"^\*\*Acceptance", line):
            in_acceptance = True
            continue
        
        # Stop acceptance section on next heading or section
        if in_acceptance and (line.startswith("#") or line.startswith("**Out of scope")):
            in_acceptance = False
        
        # Collect acceptance criteria lines
        if in_acceptance and current:
            stripped = line.strip()
            # Match numbered criteria: 1. or - item
            if re.match(r"^\d+\.|^-\s+", stripped):
                # Clean up checkmarks and formatting
                clean = re.sub(r"^[\d\.]+\s*", "", stripped)
                clean = re.sub(r"^-\s*", "", clean)
                clean = re.sub(r"✅\s*", "", clean)
                acceptance_lines.append(clean)
    
    # Save last item
    if current:
        current["acceptance"] = acceptance_lines
        items.append(current)
    
    # Find next unshipped
    next_unshipped = None
    for item in sorted(items, key=lambda x: x["num"]):
        if not item["shipped"]:
            next_unshipped = item
            break
    
    return {
        "items": items,
        "next_unshipped": next_unshipped
    }


def next_roadmap_item() -> dict | None:
    """Get the next unshipped ROADMAP item."""
    data = parse_roadmap()
    return data.get("next_unshipped")


def format_pr_title(item: dict) -> str:
    """Format PR title for a ROADMAP item."""
    return f"OpenBot self-build: {item['name']}"


def format_pr_body(item: dict) -> str:
    """Format PR body with acceptance checklist for a ROADMAP item."""
    lines = [
        f"# {item['id']}: {item['name']}",
        "",
        "This PR was auto-generated by OpenBot's self-build loop.",
        "",
        "## Acceptance Criteria",
        "",
    ]
    
    acceptance = item.get("acceptance") or []
    if acceptance:
        for idx, criterion in enumerate(acceptance, 1):
            lines.append(f"- [ ] {criterion}")
    else:
        lines.append("- [ ] Implementation complete")
        lines.append("- [ ] Tests passing")
        lines.append("- [ ] Documentation updated")
    
    lines.extend([
        "",
        "## Testing",
        "",
        "- [ ] Manual testing complete",
        "- [ ] Automated tests added/passing",
        "",
        "---",
        "",
        "*OpenBot uses Hermes Agent (MIT, Nous Research) and OpenCode (MIT, Anomaly). Not affiliated with, sponsored by, or endorsed by those projects.*"
    ])
    
    return "\n".join(lines)


def roadmap_instruction(item: dict) -> str:
    """Generate Builder instruction for implementing a ROADMAP item."""
    acceptance = item.get("acceptance") or []
    criteria_text = "\n".join(f"- {criterion}" for criterion in acceptance) if acceptance else "See ROADMAP.md for full acceptance criteria."
    
    return f"""Implement {item['id']}: {item['name']}.

Read docs/ROADMAP.md for the full specification.

Acceptance criteria:
{criteria_text}

Follow AGENTS.md and OPENBOT.md:
- Wire Hermes Agent and OpenCode binaries (do not reimplement)
- Change only glue, board, docs, and presets
- Update brains/INDEX.md when complete
- No secrets in files

Create a focused, tested implementation that meets all acceptance criteria."""
