"""WC-7: Self-Build Loop tests."""

from __future__ import annotations

import json
import os
import re
import tempfile
from pathlib import Path
from unittest.mock import MagicMock, Mock, patch

import pytest

from openbot.config import DEFAULT_SETTINGS, load_settings, save_settings
from openbot.roadmap import (
    format_pr_body,
    format_pr_title,
    next_roadmap_item,
    parse_roadmap,
    roadmap_instruction,
)
from openbot.routine_templates import expand_self_build_instruction, get_template_by_id
from openbot.routines import create_routine, execute_routine, read_routine, update_routine
from openbot.selfbuild import (
    ensure_self_build_routine,
    self_build_enabled,
    self_build_routine_exists,
    self_build_status,
)
from openbot.store import ROOT


@pytest.fixture
def temp_roadmap():
    """Create a temporary ROADMAP.md for testing."""
    roadmap_path = ROOT / "docs" / "ROADMAP.md"
    roadmap_path.parent.mkdir(parents=True, exist_ok=True)
    
    original_content = roadmap_path.read_text(encoding="utf-8") if roadmap_path.exists() else None
    
    # Create test roadmap with shipped and unshipped items
    test_content = """
# OpenBot Roadmap

### **WC-1: True Parallel Multi-Agent** ✅ SHIPPED

Multi-spawn from one message, autonomous task queue.

**Acceptance criteria:**
1. Multi-spawn from one message works
2. Autonomous queue worker picks up handoffs
3. Comprehensive tests passing

### **WC-2: Coding Worker Hardening** ✅ SHIPPED

Retry on transient failures, Accept→Revert rollback.

**Acceptance criteria:**
1. Retry logic works
2. Revert Accept button functional

### **WC-8: E2E World-Class Audit** ⭐

Cloud Agent E2E test against live Railway OpenBot.

**Acceptance criteria:**
1. Cloud Agent E2E test runs
2. Test suite passes
3. Cos world-class sign-off
4. Regression suite automated
5. Comprehensive tests passing
6. ROADMAP + INDEX updated

**Out of scope:**
- Full integration test suite
"""
    
    roadmap_path.write_text(test_content, encoding="utf-8")
    
    yield roadmap_path
    
    # Restore original content
    if original_content is not None:
        roadmap_path.write_text(original_content, encoding="utf-8")
    elif roadmap_path.exists():
        roadmap_path.unlink()


class TestRoadmapParsing:
    """Test ROADMAP.md parsing."""
    
    def test_parse_roadmap(self, temp_roadmap):
        """Parse ROADMAP and extract items."""
        data = parse_roadmap()
        
        assert "items" in data
        assert "next_unshipped" in data
        assert len(data["items"]) >= 2
        
        # Check shipped items
        wc1 = next((item for item in data["items"] if item["id"] == "WC-1"), None)
        assert wc1 is not None
        assert wc1["shipped"] is True
        assert wc1["name"] == "True Parallel Multi-Agent"
        
        wc2 = next((item for item in data["items"] if item["id"] == "WC-2"), None)
        assert wc2 is not None
        assert wc2["shipped"] is True
    
    def test_next_unshipped_item(self, temp_roadmap):
        """Get next unshipped ROADMAP item."""
        item = next_roadmap_item()
        
        assert item is not None
        assert item["id"] == "WC-8"
        assert item["name"] == "E2E World-Class Audit"
        assert item["shipped"] is False
        assert len(item["acceptance"]) >= 4
    
    def test_format_pr_title(self, temp_roadmap):
        """Format PR title from ROADMAP item."""
        item = next_roadmap_item()
        title = format_pr_title(item)
        
        assert title == "OpenBot self-build: E2E World-Class Audit"
    
    def test_format_pr_body(self, temp_roadmap):
        """Format PR body with acceptance checklist."""
        item = next_roadmap_item()
        body = format_pr_body(item)
        
        assert "WC-8: E2E World-Class Audit" in body
        assert "auto-generated by OpenBot's self-build loop" in body
        assert "- [ ] Cloud Agent E2E test runs" in body
        assert "- [ ] Comprehensive tests passing" in body
        assert "OpenBot uses Hermes Agent" in body
    
    def test_roadmap_instruction(self, temp_roadmap):
        """Generate Builder instruction from ROADMAP item."""
        item = next_roadmap_item()
        instruction = roadmap_instruction(item)
        
        assert "Implement WC-8: E2E World-Class Audit" in instruction
        assert "Acceptance criteria:" in instruction
        assert "Cloud Agent E2E test runs" in instruction
        assert "Follow AGENTS.md and OPENBOT.md" in instruction
        assert "No secrets in files" in instruction


class TestRoutineTemplate:
    """Test self-build routine template."""
    
    def test_self_build_template_exists(self):
        """Self-build template is available."""
        template = get_template_by_id("self-build")
        
        assert template is not None
        assert template["name"] == "Weekly Self-Build"
        assert template["schedule"] == "every Monday at 10am"
        assert len(template["steps"]) == 3
    
    def test_template_steps(self, temp_roadmap):
        """Self-build template has correct steps."""
        template = get_template_by_id("self-build")
        
        assert template["steps"][0]["seat"] == "builder"
        assert "WC-8: E2E World-Class Audit" in template["steps"][0]["instruction"]
        
        assert template["steps"][1]["seat"] == "think"
        assert "Review the diff for correctness" in template["steps"][1]["instruction"]
        
        assert template["steps"][2]["seat"] == "ops"
        assert "Open a PR" in template["steps"][2]["instruction"]
    
    def test_expand_self_build_instruction(self, temp_roadmap):
        """Expand self-build instruction dynamically."""
        instruction = expand_self_build_instruction()
        
        assert "Implement WC-8: E2E World-Class Audit" in instruction
        assert "Acceptance criteria:" in instruction


class TestSettings:
    """Test enable_self_build settings."""
    
    def test_default_setting(self):
        """Self-build is disabled by default."""
        assert DEFAULT_SETTINGS["enable_self_build"] is False
    
    def test_save_and_load_setting(self):
        """Save and load enable_self_build setting."""
        # Save enabled
        save_settings({"enable_self_build": True})
        settings = load_settings()
        assert settings["enable_self_build"] is True
        
        # Save disabled
        save_settings({"enable_self_build": False})
        settings = load_settings()
        assert settings["enable_self_build"] is False


class TestSelfBuildManagement:
    """Test self-build routine management."""
    
    def test_self_build_enabled(self):
        """Check if self-build is enabled."""
        save_settings({"enable_self_build": False})
        assert self_build_enabled() is False
        
        save_settings({"enable_self_build": True})
        assert self_build_enabled() is True
        
        # Restore default
        save_settings({"enable_self_build": False})
    
    def test_ensure_routine_when_disabled(self):
        """When disabled, routine is not created."""
        save_settings({"enable_self_build": False})
        
        result = ensure_self_build_routine()
        
        assert result["ok"] is True
        assert result["action"] in {"skipped", "disabled"}
    
    def test_ensure_routine_when_enabled(self, temp_roadmap):
        """When enabled, routine is created with fixed ID."""
        save_settings({"enable_self_build": True})
        
        result = ensure_self_build_routine()
        
        assert result["ok"] is True
        assert result["action"] in {"created", "exists", "enabled"}
        assert result["routine_id"] == "routine-selfbuild"
        
        # Check routine was created with fixed ID
        assert self_build_routine_exists() is True
        
        routine = read_routine("routine-selfbuild", None)
        assert routine is not None
        assert routine["name"] == "Weekly Self-Build"
        assert routine["enabled"] is True
        assert len(routine["steps"]) == 3
        
        # Verify file path uses fixed ID
        from openbot.routines import routine_path
        path = routine_path("routine-selfbuild", None)
        assert path.exists()
        assert path.name == "routine-selfbuild.md"
        
        # Cleanup
        save_settings({"enable_self_build": False})
        ensure_self_build_routine()
    
    def test_stable_routine_id_no_duplicates(self, temp_roadmap):
        """Enabling twice does not create duplicate routines."""
        save_settings({"enable_self_build": False})
        
        # Enable first time
        save_settings({"enable_self_build": True})
        result1 = ensure_self_build_routine()
        assert result1["ok"] is True
        assert result1["action"] == "created"
        assert result1["routine_id"] == "routine-selfbuild"
        
        # Enable second time (should not create duplicate)
        result2 = ensure_self_build_routine()
        assert result2["ok"] is True
        assert result2["action"] in {"exists", "enabled"}
        assert result2["routine_id"] == "routine-selfbuild"
        
        # Verify only one routine file exists
        from openbot.routines import routine_dir
        folder = routine_dir(None)
        routine_files = list(folder.glob("routine-*.md"))
        selfbuild_files = [f for f in routine_files if "selfbuild" in f.name]
        assert len(selfbuild_files) == 1
        assert selfbuild_files[0].name == "routine-selfbuild.md"
        
        # Cleanup
        save_settings({"enable_self_build": False})
        ensure_self_build_routine()
    
    def test_disable_existing_routine(self, temp_roadmap):
        """Disabling flag disables the routine."""
        # Enable first
        save_settings({"enable_self_build": True})
        ensure_self_build_routine()
        assert self_build_routine_exists() is True
        
        # Disable
        save_settings({"enable_self_build": False})
        result = ensure_self_build_routine()
        
        assert result["ok"] is True
        assert result["action"] == "disabled"
        
        routine = read_routine("routine-selfbuild", None)
        assert routine is not None
        assert routine["enabled"] is False
    
    def test_self_build_status(self, temp_roadmap):
        """Get self-build status."""
        save_settings({"enable_self_build": False})
        
        status = self_build_status()
        
        assert "enabled" in status
        assert "routine_exists" in status
        assert "next_item" in status
        
        assert status["enabled"] is False
        assert status["next_item"]["id"] == "WC-8"


class TestOpenCodeGoEnforcement:
    """Test that self-build jobs use OpenCode Go wallets."""
    
    @patch("openbot.router.activate_account")
    @patch("openbot.router.keyring")
    def test_force_go_wallet_for_self_build(self, mock_keyring, mock_activate):
        """Self-build jobs enforce OpenCode Go wallets."""
        from openbot.router import _activate
        
        # Mock keyring with Go and PAYG accounts
        mock_keyring.return_value = {
            "accounts": [
                {"id": "acc-go-1", "provider": "opencode", "label": "OpenCode Go Shared", "key": "sk-go-1"},
                {"id": "acc-payg-1", "provider": "openrouter", "label": "OpenRouter PAYG", "key": "sk-or-1"},
            ]
        }
        
        mock_activate.return_value = "acc-go-1"
        
        # Call with force_go=True
        result = _activate("OpenCode", None, None, force_go=True)
        
        # Should activate Go wallet
        mock_activate.assert_called_once_with("acc-go-1")
        assert result == "acc-go-1"
    
    @patch("openbot.router.activate_for_engine")
    @patch("openbot.router.keyring")
    def test_normal_activation_without_force(self, mock_keyring, mock_activate_for_engine):
        """Normal jobs use standard wallet selection."""
        from openbot.router import _activate
        
        mock_keyring.return_value = {"accounts": []}
        mock_activate_for_engine.return_value = "acc-default"
        
        # Call without force_go
        result = _activate("OpenCode", None, None, force_go=False)
        
        # Should use normal activation
        mock_activate_for_engine.assert_called_once()


class TestExecuteRoutine:
    """Test routine execution with self-build."""
    
    @patch("openbot.router.handle")
    def test_execute_self_build_routine(self, mock_handle, temp_roadmap):
        """Execute self-build routine."""
        save_settings({"enable_self_build": True})
        ensure_self_build_routine()
        
        # Mock successful job returns
        mock_handle.side_effect = [
            {
                "id": "job-builder-123",
                "text": "Implemented WC-8 with tests",
                "blocker": None,
                "stopped": False,
            },
            {
                "id": "job-think-456",
                "text": "Diff looks good, follows AGENTS.md",
                "blocker": None,
                "stopped": False,
            },
            {
                "id": "job-ops-789",
                "text": "PR opened: #42",
                "blocker": None,
                "stopped": False,
            },
        ]
        
        result = execute_routine("routine-selfbuild", None)
        
        assert result["ok"] is True
        assert result["status"] == "completed"
        assert result["completed_steps"] == 3
        assert result["total_steps"] == 3
        assert len(result["results"]) == 3
        
        # Verify handle was called with correct parameters
        assert mock_handle.call_count == 3
        
        # Check first call (Builder)
        call_args = mock_handle.call_args_list[0]
        assert "Implement WC-8" in call_args[0][0]  # prompt
        assert call_args[1]["preset"] == "builder"
        
        # Cleanup
        save_settings({"enable_self_build": False})
        ensure_self_build_routine()


class TestIntegration:
    """Integration tests."""
    
    @patch("openbot.routines.attach_routine_cron")
    def test_full_flow_enable_to_routine(self, mock_attach_cron, temp_roadmap):
        """Full flow: enable setting → create routine → attach cron."""
        mock_attach_cron.return_value = {"ok": True}
        
        # Start disabled
        save_settings({"enable_self_build": False})
        assert self_build_enabled() is False
        
        # Enable
        save_settings({"enable_self_build": True})
        result = ensure_self_build_routine()
        
        assert result["ok"] is True
        assert result["action"] in {"created", "exists"}
        
        # Verify routine created
        routine = read_routine("routine-selfbuild", None)
        assert routine is not None
        assert routine["enabled"] is True
        
        # Verify cron attached
        if result["action"] == "created":
            mock_attach_cron.assert_called_once_with("routine-selfbuild", None)
        
        # Cleanup
        save_settings({"enable_self_build": False})
        ensure_self_build_routine()


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
